Added C# example of graceful shutdown of a AWS Lambda
aws-samples/graceful-shutdown-with-aws-lambda pull request #5
Opened 2023-10-30 14:46 UTC by meijeran

*Description of changes:*
Added a C# example of graceful shutdown of a AWS Lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-31 01:25 UTC, bnusunny requested changes
Can you move this line into the constructor? This only needs to run once when an instance is created.

2023-10-31 11:43 UTC, meijeran commented
@bnusunny I didn't what line you mentioned but I assume it was about the handler registration. I moved it to the constructor.

2023-11-01 07:39 UTC, bnusunny requested changes
A few minor issues. Could you update the PR?

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/template.yaml
> +    Value: !GetAtt MyDotNetFunction.Arn
`MyDotNetFunction` does not exist. This should be `HelloWorldFunction`.

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/template.yaml
> +        - arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14
Should add `!Sub` here to use cloudformation variables. 

```yaml
        - !Sub arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14
 ```

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/template.yaml
> +      Handler: HelloWorld.Function::FunctionHandler
Handler is not correct. Should be the following: 

```yaml
      Handler: HelloWorldFunction::HelloWorldFunction.Function::FunctionHandler
```

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/template.yaml
> +    Value: !GetAtt MyDotNetFunctionRole.Arn
Same here. `MyDotNetFunction` does not exist.

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/README.md
> +Take note of the output value of HelloWorldApi. Use curl to invoke the api and trigger the lambda function once.
`HelloWorldApi` should match the Output in Sam template.

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/README.md
> +curl "replace this with value of HelloWorldApi"
`HelloWorldApi` should match the Output in Sam template.

2023-11-01 07:39 UTC, bnusunny commented on csharp-demo/src/HelloWorldFunction/Function.cs
> +        return request.Body?.ToUpper();
This response does not match API Gateway proxy response format. Could be updated as something like below. 

```csharp
    public APIGatewayProxyResponse FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context)
    {   
        return new APIGatewayProxyResponse{
            StatusCode = 200,
            Body = "Hello world!",
        };
         
    }
```

2023-11-01 08:21 UTC, bnusunny commented
Looks good. Thank you for the contribution!

2023-11-01 08:22 UTC, merged